### ISSUE TITLE
can't create account anymore

### ISSUE THREAD

**Issue by Foxtrod89** [CarloDePieri/pymailtm#13]

**Comment by CarloDePieri** [comment]
Quick update: while [the mail.tm web page](https://mail.tm/) is up, [their web API](https://api.mail.tm/) is currently offline for some reason. I contacted their support to see what's going on, but until they resolve the problem there's nothing I can do about it... I'll keep this issue open for now to track the incident.

**Comment by CarloDePieri** [comment]
They got back to me, they are aware of the issue and are working on a fix!
