### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by anon-user-com** [CarloDePieri/pymailtm#4]
How can I use mail.tm api in python I neeed some help to use it. Thanks

**Comment by CarloDePieri** [comment]
Hi. Your question is way to broad for a github issue (this is not really the place for a tutorial).

You can find code that uses the api [here](https://github.com/CarloDePieri/pymailtm/blob/master/pymailtm/pymailtm.py)...

... sadly, I'm well aware that file is a mess (the api is intertwined with the code that uses it) and there's no documentation. I'm trying to fix this with [v2](https://github.com/CarloDePieri/pymailtm/projects/1) but RL keeps getting in the way :/

**Comment by anon-user-com** [comment]
> Hi. Your question is way to broad for a github issue (this is not really the place for a tutorial).
> 
> 
> 
> You can find code that uses the api [here](https://github.com/CarloDePieri/pymailtm/blob/master/pymailtm/pymailtm.py)...
> 
> 
> 
> ... sadly, I'm well aware that file is a mess (the api is intertwined with the code that uses it) and there's no documentation. I'm trying to fix this with [v2](https://github.com/CarloDePieri/pymailtm/projects/1) but RL keeps getting in the way :/

Okay thanks I will see it.

**Comment by CarloDePieri** [comment]
Other examples can currently be found in the related [tests](https://github.com/CarloDePieri/pymailtm/blob/master/tests/test_pymailtm.py). Since tests have natural language descriptions, they may help you as well.
