### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by metin02oktay** [CarloDePieri/pymailtm#5]
```

input:  pip install pymailtm
output:

Collecting pymailtm
  Could not find a version that satisfies the requirement pymailtm (from versions: )
No matching distribution found for pymailtm



input:   pip install git+https://github.com/CarloDePieri/pymailtm.git
output:

Collecting git+https://github.com/CarloDePieri/pymailtm.git
  Cloning https://github.com/CarloDePieri/pymailtm.git to /tmp/pip-7u2r_2c4-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-7u2r_2c4-build/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-7u2r_2c4-build/


```

Install command with pip error occurs. I guess because setup.py doesn't exist. Can you please add setup.py to the repo?

**Comment by CarloDePieri** [comment]
pymailtm use [poetry](https://python-poetry.org/docs/) as build system, therefore it does not need a `setup.py` (it uses `pyproject.toml` instead). Modern versions of pip understand this format.

I just confirmed that installing directly from the git repo works (pip 21.2.2, python 3.7).

Installing from pip also currently works (and does not need setup.py either, packages on pypi are pre-built).

What's your pip and python versions?

**Comment by metin02oktay** [comment]
Ubuntu 20.04

Python 3.8.10
[GCC 9.3.0] on linux

pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by metin02oktay** [comment]
It was my fault, sorry. I just upgrade my pip version and done. I installed.  Thank you.
